name: ncue_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  # firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1

  firebase_ui_auth: ^1.8.0
  firebase_ui_oauth: ^1.4.11
  firebase_ui_oauth_google: ^1.2.11
  firebase_ui_oauth_apple: ^1.2.11
  firebase_ui_oauth_facebook: ^1.2.11

  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.5
  flutter_svg: ^2.0.7
  http: ^1.1.0
  firebase_ui_localizations: ^1.6.1
  webview_flutter: ^4.2.4
  provider: ^6.0.5
  encrypt: ^5.0.1
  shared_preferences: ^2.2.1
  local_auth: ^2.1.7
  audioplayers: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/src/icons/app_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/src/icons/
    - lib/src/sounds/
