name: ncue.aiot_app
description: NCUE team
publish_to: 'none'

version: 7.0.0+13

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1

  firebase_ui_auth: ^1.8.0
  firebase_ui_oauth: ^1.4.11
  firebase_ui_oauth_google: ^1.2.11
  firebase_ui_oauth_apple: ^1.2.11
  firebase_ui_oauth_facebook: ^1.2.11

  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.5
  flutter_svg: ^2.0.7
  http: ^1.1.0
  firebase_ui_localizations: ^1.6.1

  # basics
  local_auth: ^2.1.7
  audioplayers: ^5.1.0

  # local storage
  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  # webview
  webview_flutter: ^4.2.4
  provider: ^6.0.5
  encrypt: ^5.0.1
  shared_preferences: ^2.2.1
  json_model: 1.0.0
  json_annotation: ^4.8.1

  #bluetooth
  flutter_blue_plus: ^1.11.8
  permission_handler: ^10.4.3
  cupertino_icons: ^1.0.2

  #mqtt
  mqtt_client: ^9.8.1
  intl: any

  #sensors
  lottie: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/src/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/src/icons/app_icon.png"
  windows:
    generate: true
    image_path: "lib/src/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/src/icons/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - lib/src/icons/
    - lib/src/sounds/
    - assets/
    - assets/lottie/day.json
    - assets/lottie/LightRain.json
